# Usa un'immagine di base Python ufficiale
FROM python:3.11-slim

# Imposta la directory di lavoro
WORKDIR /app

# Copia i file nella directory di lavoro
COPY . /app

#creare una cartella che si chiama reports
RUN mkdir reports

# Installa le dipendenze specificate in requirements.txt
RUN python -m pip install --no-cache-dir -r requirements.txt

RUN --mount=type=secret,id=API_OPENAI \
    export OPENAI_KEY=$(cat /run/secrets/API_OPENAI)

# Comando di default: avvia una shell Python interattiva
CMD ["python"]