FROM selenium/standalone-chrome:latest

USER root

# Installa Python + dipendenze
RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*

# Imposta la directory di lavoro
WORKDIR /app

# Copia i file nella directory di lavoro
COPY . /app

# Crea cartelle necessarie
RUN mkdir reports
RUN mkdir img

# Installa le dipendenze specificate in requirements.txt
RUN python -m pip install --no-cache-dir -r requirements.txt

RUN --mount=type=secret,id=API_OPENAI \
    export OPENAI_KEY=$(cat /run/secrets/API_OPENAI)

# Il log.txt sarà disponibile nella directory /app
# Puoi visualizzarlo con: docker exec <container_name> cat log.txt
# O copiarlo con: docker cp <container_name>:/app/log.txt .

# Comando di default: esegui lo script Python
CMD ["python3", "new_create_report.py"]